import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
    troubleshootingSidebar: [{type: 'autogenerated', dirName: 'troubleshooting'}], // Adjust `dirName` as needed
    changelogSidebar: [{type: 'autogenerated', dirName: 'changelog'}], // Adjust `dirName` as needed
    docsSidebar: [
        {
            type: 'category',
            label: 'Getting Started',
            collapsed: false,
            items: ['index'],
        },
        'intro/quickstart',
        {
            type: 'category',
            label: 'Before You Begin',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'intro/before-you-begin'
                }
            ],
        },
        {
            type: 'category',
            label: 'Understanding FlutterFlow UI',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'intro/ff-ui'
                }
            ],
        },
        {
            type: 'category',
            label: 'Resources',
            collapsed: false,
            link: {
                type: 'generated-index',
                title: 'FlutterFlow Resources',
                description: 'Learn about the key building blocks in FlutterFlow',
                slug: '/resources',
                keywords: ['resources'],
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'resources'
                }
            ],
        },
        {
            type: 'category',
            label: 'Building Concepts',
            collapsed: false,
            link: {
                type: 'generated-index',
                title: 'Key Concepts',
                description: 'Learn about the key concepts important for building with FlutterFlow',
                slug: '/concepts',
                keywords: ['concepts'],
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'ff-concepts'
                }
            ],
        },
        {
            type: 'category',
            label: 'Testing & Publishing',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'testing-deployment-publishing'
                }
            ],
        },
        {
            type: 'category',
            label: 'Integrations',
            collapsed: true,
            link: {
                type: 'generated-index',
                title: 'FF Guides',
                description: 'Learn about the various integrations available in FlutterFlow!',
                slug: '/integrations',
                keywords: ['guides'],
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'ff-integrations'
                }
            ],
        }
    ]
};

export default sidebars;
