import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: ''}], // Example configuration
  // introSidebar: [{type: 'autogenerated', dirName: 'intro'}], // Example configuration
  troubleshootingSidebar: [{type: 'autogenerated', dirName: 'troubleshooting'}], // Adjust `dirName` as needed
  docsSidebar : [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['index', {type: 'category', label: "Before You Begin", items: [
        'intro/before-you-begin/setting-up-flutterflow', 'intro/before-you-begin/app-architecture'
    ]}],
    }
  ]
};

export default sidebars;
