name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Automatic build on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: List Build Directory
        run: ls -R ./build  # Ensure build output is correct

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}